---
title: "CodeBook"
author: "James Barnes"
date: "January 26, 2016"
output: html_document
---
<b>Data Source:</b>
run_analysis.r script reads data from the UCI HAR data set and transforms the data into a tidy data set as specified in the requirements for the project.  The oritignal source data for the UCI HAR dataset is located here:

https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip

Attribution for the original UCI HAT dataset goes to:
==================================================================
Human Activity Recognition Using Smartphones Dataset
Version 1.0
==================================================================
Jorge L. Reyes-Ortiz, Davide Anguita, Alessandro Ghio, Luca Oneto.
Smartlab - Non Linear Complex Systems Laboratory
DITEN - Università degli Studi di Genova.
Via Opera Pia 11A, I-16145, Genoa, Italy.
activityrecognition@smartlab.ws
www.smartlab.ws
==================================================================

<b>Transformations performed in run_analysis.r:</b>
The original dataset contains test and training data.  run_analysis.r does the following:
-1.Merges the training and the test sets to create one data set.
-2.Extracts only the measurements on the mean and standard deviation for each measurement.
-3.Uses descriptive activity names from the activities labels file to name the activities in the data set
-4.Appropriately labels the data set with descriptive variable names by removing punctuation from the original names.  This data set is named newDF in run_analysis.r.
-5.From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.  This data set is named TidyData in run_analysis.r.

<b>Meta Data for newDF and TidyData data sets created by run_analysis.r:</b>

NewDF
str(newDF)
'data.frame':	10299 obs. of  70 variables:
 $ ID                      : int  1 2 3 4 5 6 7 8 9 10 ...
 $ Activity                : int  5 5 5 5 5 5 5 5 5 5 ...
 $ Subject                 : int  2 2 2 2 2 2 2 2 2 2 ...
 $ tBodyAccMeanX           : num  0.257 0.286 0.275 0.27 0.275 ...
 $ tBodyAccMeanY           : num  -0.0233 -0.0132 -0.0261 -0.0326 -0.0278 ...
 $ tBodyAccMeanZ           : num  -0.0147 -0.1191 -0.1182 -0.1175 -0.1295 ...
 $ tBodyAccStdX            : num  -0.938 -0.975 -0.994 -0.995 -0.994 ...
 $ tBodyAccStdY            : num  -0.92 -0.967 -0.97 -0.973 -0.967 ...
 $ tBodyAccStdZ            : num  -0.668 -0.945 -0.963 -0.967 -0.978 ...
 $ tGravityAccMeanX        : num  0.936 0.927 0.93 0.929 0.927 ...
 $ tGravityAccMeanY        : num  -0.283 -0.289 -0.288 -0.293 -0.303 ...
 $ tGravityAccMeanZ        : num  0.115 0.153 0.146 0.143 0.138 ...
 $ tGravityAccStdX         : num  -0.925 -0.989 -0.996 -0.993 -0.996 ...
 $ tGravityAccStdY         : num  -0.937 -0.984 -0.988 -0.97 -0.971 ...
 $ tGravityAccStdZ         : num  -0.564 -0.965 -0.982 -0.992 -0.968 ...
 $ tBodyAccJerkMeanX       : num  0.072 0.0702 0.0694 0.0749 0.0784 ...
 $ tBodyAccJerkMeanY       : num  0.04575 -0.01788 -0.00491 0.03227 0.02228 ...
 $ tBodyAccJerkMeanZ       : num  -0.10604 -0.00172 -0.01367 0.01214 0.00275 ...
 $ tBodyAccJerkStdX        : num  -0.907 -0.949 -0.991 -0.991 -0.992 ...
 $ tBodyAccJerkStdY        : num  -0.938 -0.973 -0.971 -0.973 -0.979 ...
 $ tBodyAccJerkStdZ        : num  -0.936 -0.978 -0.973 -0.976 -0.987 ...
 $ tBodyGyroMeanX          : num  0.11998 -0.00155 -0.04821 -0.05664 -0.05999 ...
 $ tBodyGyroMeanY          : num  -0.0918 -0.1873 -0.1663 -0.126 -0.0847 ...
 $ tBodyGyroMeanZ          : num  0.1896 0.1807 0.1542 0.1183 0.0787 ...
 $ tBodyGyroStdX           : num  -0.883 -0.926 -0.973 -0.968 -0.975 ...
 $ tBodyGyroStdY           : num  -0.816 -0.93 -0.979 -0.975 -0.978 ...
 $ tBodyGyroStdZ           : num  -0.941 -0.968 -0.976 -0.963 -0.968 ...
 $ tBodyGyroJerkMeanX      : num  -0.2049 -0.1387 -0.0978 -0.1022 -0.0918 ...
 $ tBodyGyroJerkMeanY      : num  -0.1745 -0.0258 -0.0342 -0.0447 -0.029 ...
 $ tBodyGyroJerkMeanZ      : num  -0.0934 -0.0714 -0.06 -0.0534 -0.0612 ...
 $ tBodyGyroJerkStdX       : num  -0.901 -0.962 -0.984 -0.984 -0.988 ...
 $ tBodyGyroJerkStdY       : num  -0.911 -0.956 -0.988 -0.99 -0.992 ...
 $ tBodyGyroJerkStdZ       : num  -0.939 -0.981 -0.976 -0.981 -0.982 ...
 $ tBodyAccMagMean         : num  -0.867 -0.969 -0.976 -0.974 -0.976 ...
 $ tBodyAccMagStd          : num  -0.705 -0.954 -0.979 -0.977 -0.977 ...
 $ tGravityAccMagMean      : num  -0.867 -0.969 -0.976 -0.974 -0.976 ...
 $ tGravityAccMagStd       : num  -0.705 -0.954 -0.979 -0.977 -0.977 ...
 $ tBodyAccJerkMagMean     : num  -0.93 -0.974 -0.982 -0.983 -0.987 ...
 $ tBodyAccJerkMagStd      : num  -0.896 -0.941 -0.971 -0.975 -0.989 ...
 $ tBodyGyroMagMean        : num  -0.796 -0.898 -0.939 -0.947 -0.957 ...
 $ tBodyGyroMagStd         : num  -0.762 -0.911 -0.972 -0.97 -0.969 ...
 $ tBodyGyroJerkMagMean    : num  -0.925 -0.973 -0.987 -0.989 -0.99 ...
 $ tBodyGyroJerkMagStd     : num  -0.894 -0.944 -0.984 -0.986 -0.99 ...
 $ fBodyAccMeanX           : num  -0.919 -0.961 -0.992 -0.993 -0.992 ...
 $ fBodyAccMeanY           : num  -0.918 -0.964 -0.965 -0.968 -0.969 ...
 $ fBodyAccMeanZ           : num  -0.789 -0.957 -0.967 -0.967 -0.98 ...
 $ fBodyAccStdX            : num  -0.948 -0.984 -0.995 -0.996 -0.995 ...
 $ fBodyAccStdY            : num  -0.925 -0.97 -0.974 -0.977 -0.967 ...
 $ fBodyAccStdZ            : num  -0.636 -0.942 -0.962 -0.969 -0.978 ...
 $ fBodyAccJerkMeanX       : num  -0.9 -0.944 -0.991 -0.991 -0.991 ...
 $ fBodyAccJerkMeanY       : num  -0.937 -0.969 -0.973 -0.972 -0.98 ...
 $ fBodyAccJerkMeanZ       : num  -0.924 -0.973 -0.972 -0.97 -0.983 ...
 $ fBodyAccJerkStdX        : num  -0.924 -0.962 -0.992 -0.992 -0.994 ...
 $ fBodyAccJerkStdY        : num  -0.943 -0.98 -0.971 -0.975 -0.979 ...
 $ fBodyAccJerkStdZ        : num  -0.948 -0.981 -0.972 -0.981 -0.989 ...
 $ fBodyGyroMeanX          : num  -0.824 -0.923 -0.973 -0.972 -0.976 ...
 $ fBodyGyroMeanY          : num  -0.808 -0.926 -0.981 -0.981 -0.98 ...
 $ fBodyGyroMeanZ          : num  -0.918 -0.968 -0.972 -0.967 -0.969 ...
 $ fBodyGyroStdX           : num  -0.903 -0.927 -0.973 -0.967 -0.974 ...
 $ fBodyGyroStdY           : num  -0.823 -0.932 -0.977 -0.972 -0.977 ...
 $ fBodyGyroStdZ           : num  -0.956 -0.97 -0.979 -0.965 -0.97 ...
 $ fBodyAccMagMean         : num  -0.791 -0.954 -0.976 -0.973 -0.978 ...
 $ fBodyAccMagStd          : num  -0.711 -0.96 -0.984 -0.982 -0.979 ...
 $ fBodyBodyAccJerkMagMean : num  -0.895 -0.945 -0.971 -0.972 -0.987 ...
 $ fBodyBodyAccJerkMagStd  : num  -0.896 -0.934 -0.97 -0.978 -0.99 ...
 $ fBodyBodyGyroMagMean    : num  -0.771 -0.924 -0.975 -0.976 -0.977 ...
 $ fBodyBodyGyroMagStd     : num  -0.797 -0.917 -0.974 -0.971 -0.97 ...
 $ fBodyBodyGyroJerkMagMean: num  -0.89 -0.952 -0.986 -0.986 -0.99 ...
 $ fBodyBodyGyroJerkMagStd : num  -0.907 -0.938 -0.983 -0.986 -0.991 ...
 $ ActivityLabel           : chr  "STANDING" "STANDING" "STANDING" "STANDING" ...

TidyData
str(TidyData)
'data.frame':	180 obs. of  68 variables:
 $ Activity                : chr  "LAYING" "SITTING" "STANDING" "WALKING" ...
 $ Subject                 : int  1 1 1 1 1 1 2 2 2 2 ...
 $ tBodyAccMeanX           : num  0.222 0.261 0.279 0.277 0.289 ...
 $ tBodyAccMeanY           : num  -0.04051 -0.00131 -0.01614 -0.01738 -0.00992 ...
 $ tBodyAccMeanZ           : num  -0.113 -0.105 -0.111 -0.111 -0.108 ...
 $ tBodyAccStdX            : num  -0.928 -0.977 -0.996 -0.284 0.03 ...
 $ tBodyAccStdY            : num  -0.8368 -0.9226 -0.9732 0.1145 -0.0319 ...
 $ tBodyAccStdZ            : num  -0.826 -0.94 -0.98 -0.26 -0.23 ...
 $ tGravityAccMeanX        : num  -0.249 0.832 0.943 0.935 0.932 ...
 $ tGravityAccMeanY        : num  0.706 0.204 -0.273 -0.282 -0.267 ...
 $ tGravityAccMeanZ        : num  0.4458 0.332 0.0135 -0.0681 -0.0621 ...
 $ tGravityAccStdX         : num  -0.897 -0.968 -0.994 -0.977 -0.951 ...
 $ tGravityAccStdY         : num  -0.908 -0.936 -0.981 -0.971 -0.937 ...
 $ tGravityAccStdZ         : num  -0.852 -0.949 -0.976 -0.948 -0.896 ...
 $ tBodyAccJerkMeanX       : num  0.0811 0.0775 0.0754 0.074 0.0542 ...
 $ tBodyAccJerkMeanY       : num  0.003838 -0.000619 0.007976 0.028272 0.02965 ...
 $ tBodyAccJerkMeanZ       : num  0.01083 -0.00337 -0.00369 -0.00417 -0.01097 ...
 $ tBodyAccJerkStdX        : num  -0.9585 -0.9864 -0.9946 -0.1136 -0.0123 ...
 $ tBodyAccJerkStdY        : num  -0.924 -0.981 -0.986 0.067 -0.102 ...
 $ tBodyAccJerkStdZ        : num  -0.955 -0.988 -0.992 -0.503 -0.346 ...
 $ tBodyGyroMeanX          : num  -0.0166 -0.0454 -0.024 -0.0418 -0.0351 ...
 $ tBodyGyroMeanY          : num  -0.0645 -0.0919 -0.0594 -0.0695 -0.0909 ...
 $ tBodyGyroMeanZ          : num  0.1487 0.0629 0.0748 0.0849 0.0901 ...
 $ tBodyGyroStdX           : num  -0.874 -0.977 -0.987 -0.474 -0.458 ...
 $ tBodyGyroStdY           : num  -0.9511 -0.9665 -0.9877 -0.0546 -0.1263 ...
 $ tBodyGyroStdZ           : num  -0.908 -0.941 -0.981 -0.344 -0.125 ...
 $ tBodyGyroJerkMeanX      : num  -0.1073 -0.0937 -0.0996 -0.09 -0.074 ...
 $ tBodyGyroJerkMeanY      : num  -0.0415 -0.0402 -0.0441 -0.0398 -0.044 ...
 $ tBodyGyroJerkMeanZ      : num  -0.0741 -0.0467 -0.049 -0.0461 -0.027 ...
 $ tBodyGyroJerkStdX       : num  -0.919 -0.992 -0.993 -0.207 -0.487 ...
 $ tBodyGyroJerkStdY       : num  -0.968 -0.99 -0.995 -0.304 -0.239 ...
 $ tBodyGyroJerkStdZ       : num  -0.958 -0.988 -0.992 -0.404 -0.269 ...
 $ tBodyAccMagMean         : num  -0.8419 -0.9485 -0.9843 -0.137 0.0272 ...
 $ tBodyAccMagStd          : num  -0.7951 -0.9271 -0.9819 -0.2197 0.0199 ...
 $ tGravityAccMagMean      : num  -0.8419 -0.9485 -0.9843 -0.137 0.0272 ...
 $ tGravityAccMagStd       : num  -0.7951 -0.9271 -0.9819 -0.2197 0.0199 ...
 $ tBodyAccJerkMagMean     : num  -0.9544 -0.9874 -0.9924 -0.1414 -0.0894 ...
 $ tBodyAccJerkMagStd      : num  -0.9282 -0.9841 -0.9931 -0.0745 -0.0258 ...
 $ tBodyGyroMagMean        : num  -0.8748 -0.9309 -0.9765 -0.161 -0.0757 ...
 $ tBodyGyroMagStd         : num  -0.819 -0.935 -0.979 -0.187 -0.226 ...
 $ tBodyGyroJerkMagMean    : num  -0.963 -0.992 -0.995 -0.299 -0.295 ...
 $ tBodyGyroJerkMagStd     : num  -0.936 -0.988 -0.995 -0.325 -0.307 ...
 $ fBodyAccMeanX           : num  -0.9391 -0.9796 -0.9952 -0.2028 0.0382 ...
 $ fBodyAccMeanY           : num  -0.86707 -0.94408 -0.97707 0.08971 0.00155 ...
 $ fBodyAccMeanZ           : num  -0.883 -0.959 -0.985 -0.332 -0.226 ...
 $ fBodyAccStdX            : num  -0.9244 -0.9764 -0.996 -0.3191 0.0243 ...
 $ fBodyAccStdY            : num  -0.834 -0.917 -0.972 0.056 -0.113 ...
 $ fBodyAccStdZ            : num  -0.813 -0.934 -0.978 -0.28 -0.298 ...
 $ fBodyAccJerkMeanX       : num  -0.9571 -0.9866 -0.9946 -0.1705 -0.0277 ...
 $ fBodyAccJerkMeanY       : num  -0.9225 -0.9816 -0.9854 -0.0352 -0.1287 ...
 $ fBodyAccJerkMeanZ       : num  -0.948 -0.986 -0.991 -0.469 -0.288 ...
 $ fBodyAccJerkStdX        : num  -0.9642 -0.9875 -0.9951 -0.1336 -0.0863 ...
 $ fBodyAccJerkStdY        : num  -0.932 -0.983 -0.987 0.107 -0.135 ...
 $ fBodyAccJerkStdZ        : num  -0.961 -0.988 -0.992 -0.535 -0.402 ...
 $ fBodyGyroMeanX          : num  -0.85 -0.976 -0.986 -0.339 -0.352 ...
 $ fBodyGyroMeanY          : num  -0.9522 -0.9758 -0.989 -0.1031 -0.0557 ...
 $ fBodyGyroMeanZ          : num  -0.9093 -0.9513 -0.9808 -0.2559 -0.0319 ...
 $ fBodyGyroStdX           : num  -0.882 -0.978 -0.987 -0.517 -0.495 ...
 $ fBodyGyroStdY           : num  -0.9512 -0.9623 -0.9871 -0.0335 -0.1814 ...
 $ fBodyGyroStdZ           : num  -0.917 -0.944 -0.982 -0.437 -0.238 ...
 $ fBodyAccMagMean         : num  -0.8618 -0.9478 -0.9854 -0.1286 0.0966 ...
 $ fBodyAccMagStd          : num  -0.798 -0.928 -0.982 -0.398 -0.187 ...
 $ fBodyBodyAccJerkMagMean : num  -0.9333 -0.9853 -0.9925 -0.0571 0.0262 ...
 $ fBodyBodyAccJerkMagStd  : num  -0.922 -0.982 -0.993 -0.103 -0.104 ...
 $ fBodyBodyGyroMagMean    : num  -0.862 -0.958 -0.985 -0.199 -0.186 ...
 $ fBodyBodyGyroMagStd     : num  -0.824 -0.932 -0.978 -0.321 -0.398 ...
 $ fBodyBodyGyroJerkMagMean: num  -0.942 -0.99 -0.995 -0.319 -0.282 ...
 $ fBodyBodyGyroJerkMagStd : num  -0.933 -0.987 -0.995 -0.382 -0.392 ...

